CREATE TABLE IF NOT EXISTS tb_report_datasource (
  id VARCHAR(64) NOT NULL,
  name VARCHAR(128) DEFAULT NULL,
  type VARCHAR(32) DEFAULT NULL,
  host VARCHAR(128) DEFAULT NULL,
  port INT DEFAULT NULL,
  db_name VARCHAR(128) DEFAULT NULL,
  username VARCHAR(128) DEFAULT NULL,
  password VARCHAR(512) DEFAULT NULL,
  query_timeout INT DEFAULT NULL,
  url VARCHAR(512) DEFAULT NULL,
  driver_class_name VARCHAR(128) DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_report_dataset (
  id VARCHAR(64) NOT NULL,
  name VARCHAR(128) DEFAULT NULL,
  type VARCHAR(32) DEFAULT NULL,
  datasource_id VARCHAR(64) DEFAULT NULL,
  sql_text TEXT,
  api_url VARCHAR(512) DEFAULT NULL,
  api_method VARCHAR(16) DEFAULT NULL,
  api_headers TEXT,
  api_body TEXT,
  data_path VARCHAR(256) DEFAULT NULL,
  detail_path VARCHAR(256) DEFAULT NULL,
  java_bean_name VARCHAR(128) DEFAULT NULL,
  java_bean_method VARCHAR(128) DEFAULT NULL,
  json_text LONGTEXT,
  fields LONGTEXT,
  params TEXT,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_report (
  id VARCHAR(64) NOT NULL,
  name VARCHAR(128) DEFAULT NULL,
  dataset_id VARCHAR(64) DEFAULT NULL,
  template LONGTEXT,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_report_paper (
  id VARCHAR(64) NOT NULL,
  name VARCHAR(128) DEFAULT NULL,
  width INT DEFAULT NULL,
  height INT DEFAULT NULL,
  remark VARCHAR(512) DEFAULT NULL,
  sort_no INT DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_report_dict (
  id VARCHAR(64) NOT NULL,
  code VARCHAR(128) DEFAULT NULL,
  name VARCHAR(128) DEFAULT NULL,
  source_type VARCHAR(32) DEFAULT NULL,
  enabled INT DEFAULT 1,
  remark VARCHAR(512) DEFAULT NULL,
  sort_no INT DEFAULT NULL,
  api_url VARCHAR(512) DEFAULT NULL,
  api_method VARCHAR(16) DEFAULT NULL,
  api_headers TEXT,
  data_path VARCHAR(256) DEFAULT NULL,
  value_field VARCHAR(128) DEFAULT NULL,
  label_field VARCHAR(128) DEFAULT NULL,
  datasource_id VARCHAR(64) DEFAULT NULL,
  sql_text TEXT,
  cache_minutes INT DEFAULT 10,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tb_report_dict_item (
  id VARCHAR(64) NOT NULL,
  dict_id VARCHAR(64) DEFAULT NULL,
  item_value VARCHAR(256) DEFAULT NULL,
  item_label VARCHAR(512) DEFAULT NULL,
  sort_no INT DEFAULT NULL,
  enabled INT DEFAULT 1,
  remark VARCHAR(512) DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
